---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: double-quote-string-fixer
  - repo: https://github.com/claranet/pre-commit-hooks
    hooks:
      - id: gitlab-ci-local
        # optional custom config:
        args:
          - test
...
